<?php
require('./inc/models/Model.php');
require('./inc/models/MovieSeriesModel.php');
require('./inc/models/CountriesModel.php');
require('./inc/models/GenresModel.php');
require('./inc/models/UsersModel.php');
require('./inc/header.php');
require('./inc/content.php');
require('./inc/footer.php');
